# Workflow for deploying a React app (or similar static site) to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Change "main" to your default branch name if different

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"  # or any other compatible version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # or `yarn build` if you’re using Yarn

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Ensure this matches your output directory
